name: Apply generated configuration to local Kong gateway and update API documentation

on:
  push:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Apply generated configuration to local Kong gateway and update API documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Kong declarative configuration from Spec
        run: for file in ./openapi/*.yaml; do inso generate config "$file" --type declarative -o /tmp/import/${file##*/}; done;
      - name: Validate Kong declarative configuration
        run: deck validate -s /tmp/import
      - name: Deploy declarative config
        run: for file in /tmp/import/*; do deck sync --kong-addr "http://localhost/admin-api" -s /tmp/import/${file##*/} --select-tag ${file##*/}; done;